// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDilJinn9A9gLOZnqpHxVT7P0oCHGWvhU',
    appId: '1:982181068163:web:331272562c9ff6d0cacab6',
    messagingSenderId: '982181068163',
    projectId: 'robolearn-b6a71',
    authDomain: 'robolearn-b6a71.firebaseapp.com',
    storageBucket: 'robolearn-b6a71.firebasestorage.app',
    measurementId: 'G-K3W9Q6ERNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfNt4CCWmS_yJy7EnsB1p6wflUXDqe7Tg',
    appId: '1:982181068163:android:d33a099eebb4a87bcacab6',
    messagingSenderId: '982181068163',
    projectId: 'robolearn-b6a71',
    storageBucket: 'robolearn-b6a71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuQfbLbDIy8gzjqg7oKGapFR93akw_-sI',
    appId: '1:982181068163:ios:b570a64d002a4da8cacab6',
    messagingSenderId: '982181068163',
    projectId: 'robolearn-b6a71',
    storageBucket: 'robolearn-b6a71.firebasestorage.app',
    iosBundleId: 'com.example.robolearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuQfbLbDIy8gzjqg7oKGapFR93akw_-sI',
    appId: '1:982181068163:ios:b570a64d002a4da8cacab6',
    messagingSenderId: '982181068163',
    projectId: 'robolearn-b6a71',
    storageBucket: 'robolearn-b6a71.firebasestorage.app',
    iosBundleId: 'com.example.robolearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDilJinn9A9gLOZnqpHxVT7P0oCHGWvhU',
    appId: '1:982181068163:web:c837652b7985edbbcacab6',
    messagingSenderId: '982181068163',
    projectId: 'robolearn-b6a71',
    authDomain: 'robolearn-b6a71.firebaseapp.com',
    storageBucket: 'robolearn-b6a71.firebasestorage.app',
    measurementId: 'G-QZYQ7PXJ74',
  );
}
